### ISSUE TITLE
Error handling refactoring.

### ISSUE THREAD

**Issue by TornaxO7** [TornaxO7/himalaya#16]
# IMPORTANT
It looks like that [error_chain](https://github.com/rust-lang-deprecated/error-chain) is deprecated now! So I think that we should switch to another error handling-crate. I'd suggest [thiserror](https://crates.io/crates/thiserror). We could also combine it with [anyhow](https://crates.io/crates/anyhow). What do you think? @soywod

**Comment by soywod** [comment]
I agree but not in this PR. We should stick to the main goal which is refactoring the `Msg` struct. Plus there is already an issue for this (https://github.com/soywod/himalaya/issues/152). Since now it is deprecated, this issue will be a priority once your PR merged! Thanks for pointing it out.

**Comment by TornaxO7** [comment]
:+1:
