### ISSUE TITLE
Process

### ISSUE THREAD

**Issue by TornaxO7** [TornaxO7/himalaya#17]
@soywod When I started to rewatch the code I found the following:
- A robust type-safety change like [here](https://github.com/TornaxO7/himalaya/blob/mail_refactor/src/imap/model.rs#L60) wouldn't be bad: Changing the parameter type of `flags` to our struct `Flags`
Do you agree to this?

- I also found an issue when I tried to add a flag. In general I'd like to write some tests for the subcommands and so on first.

I'll wait for your respond first before I keep implementing (I've already started to adjust the `Flags` struct).

**Comment by soywod** [comment]
> * A robust type-safety change like [here](https://github.com/TornaxO7/himalaya/blob/mail_refactor/src/imap/model.rs#L60) wouldn't be bad: Changing the parameter type of `flags` to our struct `Flags`
>   Do you agree to this?

Yes indeed!



> * I also found an issue when I tried to add a flag. In general I'd like to write some tests for the subcommands and so on first.

Isn't related to https://github.com/soywod/himalaya/issues/190?

**Comment by TornaxO7** [comment]
> Isn't related to soywod#190?

Oh yes, sorry! I thought that I created this issue xD
