### ISSUE TITLE
Template shows raw data with JSON format

### ISSUE THREAD

**Issue by soywod** [TornaxO7/himalaya#23]
`himalaya --output json template reply/forward` shows the `raw` buffer data (it should be discarded). 

**[EDIT]**: in fact it should not be discarded, but it should show the raw message as string (not buffer). This way we align with the existing behaviour (it is useful for UIs).

**Comment by TornaxO7** [comment]
I don't understand what you mean. Do the raw part should be concerted into a string?

**Comment by soywod** [comment]
Yes definitely. Compare with the master branch, we have a `raw` attribute as utf8 string, not buffer.

**Comment by TornaxO7** [comment]
Aright, I'll do that tomorrow!

**Comment by TornaxO7** [comment]
Hold on, I meant today, but in the afternoon. Today is already tomorrow.
