### ISSUE TITLE
General

### ISSUE THREAD

**Issue by TornaxO7** [TornaxO7/himalaya#8]
- [x] The `From` header contains only the email address (it should contains the name if available `My Name <my@mail.com>`
- [x] The signature is missing
- [x] The `Subject` header is missing

**Comment by TornaxO7** [comment]
@soywod are you currently on this one or can I pick this up?

**Comment by soywod** [comment]
I'm on it, I already pushed some of them on `mail_refactor_fix_issues`.

**Comment by soywod** [comment]
All fixes have been pushed on `mail_refactor_fix_issues`.
